version: '3.8'

services:
    nginx:
        image: nginx:1.25-alpine
        ports:
            - "7080:80"
        volumes:
            - ./assets/site-content:/usr/share/nginx/html:rw
            - ./assets/config/nginx.conf:/etc/nginx/conf.d/default.conf:ro

    shiny:
        build:
            context: .
            dockerfile: Dockerfile
        image: aidaho-edu.uni-hohenheim.de/jbleher/shiny_thas2025:0.1
        container_name: ais_shiny
        restart: unless-stopped
        volumes:
            - ./assets/shiny:/srv/shiny-server:rw
            - ./01_data/task_7:/srv/shiny-server/data:ro
            - ./assets/logs:/var/log/shiny-server:rw
        environment:
            # not strictly required—Shiny server listens on 3838 by default
            - SHINY_PORT=3838